---
- name: Create Azure VM
  hosts: localhost
  connection: local
  vars_prompt:
    - name: password
      prompt: "Enter local administrator password"
  tasks:

  - name: Create resource group
    azure_rm_resourcegroup:
      name: sWrayAnsibleDev
      location: australiaeast
    tags:
      Name: SwrayAnsibleDev
      ChargeTo: labwellington
      Owner: swray
      AutoStop: "2"
      AutoStart: "0"

  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: sWrayAnsibleDev
      name: sWrayAnsibleDev_vNet
      address_prefixes: "10.0.0.0/16"
    tags:
      Name: SwrayAnsibleDev
      ChargeTo: labwellington
      Owner: swray
      AutoStop: "2"
      AutoStart: "0"

  - name: Add subnet
    azure_rm_subnet:
      resource_group: sWrayAnsibleDev
      name: sWrayAnsibleDev_subnet
      address_prefix: "10.0.1.0/24"
      virtual_network: sWrayAnsibleDev_vNet

  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: sWrayAnsibleDev
      allocation_method: Static
      name: sWrayAnsibleDev_pip
    register: output_ip_address
    tags:
      Name: SwrayAnsibleDev
      ChargeTo: labwellington
      Owner: swray
      AutoStop: "2"
      AutoStart: "0"

  - name: Output public IP
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}"
  
  - name: Create Network Security Group
    azure_rm_securitygroup:
      resource_group: sWrayAnsibleDev
      name: sWrayAnsibleDevSG
      rules:
        - name: 'allow_rdp'
          protocol: Tcp
          destination_port_range: 3389
          access: Allow
          priority: 1001
          direction: Inbound
        - name: 'allow_web_traffic'
          protocol: Tcp
          destination_port_range:
            - 80
            - 443
          access: Allow
          priority: 1002
          direction: Inbound
        - name: 'allow_powershell_remoting'
          protocol: Tcp
          destination_port_range: 
            - 5985
            - 5986
          access: Allow
          priority: 1003
          direction: Inbound
    tags:
      Name: SwrayAnsibleDev
      ChargeTo: labwellington
      Owner: swray
      AutoStop: "2"
      AutoStart: "0"

  - name: Create a network interface
    azure_rm_networkinterface:
      name: sWrayAnsibleDevNIC
      resource_group: sWrayAnsibleDev
      virtual_network: sWrayAnsibleDev_vNet
      subnet_name: sWrayAnsibleDev_subnet
      security_group: sWrayAnsibleDevSG
      ip_configurations:
        - name: default
          public_ip_address_name: sWrayAnsibleDev_pip
          primary: True
    tags:
      Name: SwrayAnsibleDev
      ChargeTo: labwellington
      Owner: swray
      AutoStop: "2"
      AutoStart: "0"

  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: sWrayAnsibleDev
      name: sWrayAnsibleDevVM
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      admin_password: "{{ password }}"
      network_interfaces: sWrayAnsibleDevNIC
      os_type: Windows
      image:
        offer: WindowsServer
        publisher: MicrosoftWindowsServer
        sku: 2019-Datacenter
        version: latest
    no_log: true
    tags:
      Name: SwrayAnsibleDev
      ChargeTo: labwellington
      Owner: swray
      AutoStop: "2"
      AutoStart: "0"

  - name: Create VM script extension to enable HTTPS WinRM listener
    azure_rm_virtualmachineextension:
      name: winrm-extension
      resource_group: sWrayAnsibleDev
      virtual_machine_name: sWrayAnsibleDevVM
      publisher: Microsoft.Compute
      virtual_machine_extension_type: CustomScriptExtension
      type_handler_version: '1.9'
      settings: '{"fileUris": ["https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1"],"commandToExecute": "powershell -ExecutionPolicy Unrestricted -File ConfigureRemotingForAnsible.ps1"}'
      auto_upgrade_minor_version: true

  - name: Get facts for one Public IP
    azure_rm_publicipaddress_info:
      resource_group: sWrayAnsibleDev
      name: sWrayAnsibleDev_pip
    register: publicipaddresses

  - name: set public ip address fact
    set_fact: publicipaddress="{{ publicipaddresses | json_query('publicipaddresses[0].ip_address')}}"

  - name: wait for the WinRM port to come online
    wait_for:
      port: 5986
      host: '{{ publicipaddress }}'
	timeout: 600

