---
- name: Create Azure Environment
  hosts: localhost
  connection: local
  vars_prompt:
    - name: password
      prompt: "Enter local administrator password"
  tasks:
    - name: IncludeVars
      include_vars: inventory/vars/azure_environment.yml
      tags:
      - always
      
    - name: Create Azure Network
      import_role:
        name: azure_network
      tags:
      - createcentosvm
      - createwinvm
      - createbastion
      
    - name: Create a CentOS VM
      import_role:
        name: azure_vm
      tags:
      - createcentosvm
      
    - name: Create a bastion
      import_role:
        name: azure_bastion
      tags:
      - createbastion

    - name: Create a Windows VM
      import_role:
        name: azure_winvm
      tags:
      - createwinvm

    - name: Destroy a VM
      import_role:
        name: destroy_vm
      tags:
      - never
      - destroy
      
