---
- name: Deleting resource group - "{{ resource_group }}"
  azure_rm_resourcegroup:
    name: "{{ resource_group }}"
    state: absent
    force_delete_nonempty: true
  register: rg
- debug:
    var: rg

