---
- name: "Add subnet for bastion: {{bastion}}"
  azure_rm_subnet:
    resource_group: "{{resource_group}}"
    name: "{{bastion_subnet}}"
    address_prefix: "10.0.2.0/24"
    virtual_network: "{{virtual_network}}"

- name: "Get facts about bastion subnet for {{bastion}}"
  azure_rm_subnet_info:
    resource_group: "{{resource_group}}"
    virtual_network_name: "{{virtual_network}}"
    name: "{{bastion_subnet}}"
  register: "azure_bastion_subnet"

#- name: "Show azure_bastion_subnet for {{bastion}}"
#  debug:
#    msg: "{{azure_bastion_subnet}}"
    
- name: "Set the bastion subnet ID for {{bastion}} using the fact we just grabbed"
  set_fact:
    bastion_subnet_id: "{{azure_bastion_subnet.subnets[0].id}}"

#- name: "Show bastion subnet ID for {{bastion}}"
#  debug:
#    msg: "{{bastion_subnet_id}}"
    
- name: "Create public IP address for bastion: {{bastion}}"
  azure_rm_publicipaddress:
    resource_group: "{{resource_group}}"
    name: "{{bastion_public_ip}}"
    sku: Standard
    allocation_method: Static
    tags:
      Name: "{{resource_group}}"
      ChargeTo: "{{charge_to}}"
      Owner: "{{owner}}"
      AutoStop: "2"
      AutoStart: "0"
  register: bastion_ip_address

- name: "Get facts about public IP for bastion: {{bastion}}"
  azure_rm_publicipaddress_info:
    resource_group: "{{resource_group}}"
    name: "{{bastion_public_ip}}"
  register: "azure_bastion_publicip"

- name: "Set the publicipaddress ID using the fact we just grabbed for {{bastion}}"
  set_fact:
    bastion_publicipaddress_id: "{{azure_bastion_publicip.publicipaddresses[0].id}}"

#- name: "Show azure_bastion_publicip for {{bastion}}"
#  debug:
#    msg: "{{azure_bastion_publicip}}"

#- name: "Show publicipaddress ID for bastion: {{bastion}}"
#  debug:
#    msg: "{{bastion_publicipaddress_id}}"
    
- name: "Output IP for bastion: {{bastion}}"
  debug:
    msg: "The public IP is {{ bastion_ip_address.state.ip_address }}"
    
- name: "Create bastion: {{bastion}}"
  azure_rm_resource:
    resource_name: "{{bastion}}"
    resource_group: "{{resource_group}}"
    provider: network
    resource_type: bastionHosts
    body:
      location: "{{location}}"
      properties:
        ipconfigurations:
          - name: IpConf
            properties:
              subnet:
                id: "{{ bastion_subnet_id }}"
              publicipaddress:
                id: "{{ bastion_publicipaddress_id }}"
  
